import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { Activity, BellRing, Plus, ShieldCheck } from 'lucide-react'
import {
  demoMonitors,
  type IntegrationCatalogItem,
  type IntegrationEvent,
  type IntegrationType,
  type IntegrationViewModel,
  type MonitorViewModel,
} from '../../data'
import { Button, FeedbackBanner, Field, Modal, Select, Toggle } from '../../components/ui'
import type { IntegrationInput } from './types'
import { useI18n } from '../../app/I18nProvider'

interface ProviderField {
  key: string
  label: string
  type?: 'text' | 'password' | 'url' | 'email' | 'tel'
  placeholder: string
  hint?: string
  required?: boolean
}

const providerFields: Readonly<Record<IntegrationType, readonly ProviderField[]>> = {
  slack: [{ key: 'url', label: 'Slack webhook URL', type: 'url', placeholder: 'https://…', hint: 'Incoming webhook URL from your Slack app.', required: true }],
  microsoft_teams: [{ key: 'url', label: 'Teams workflow URL', type: 'url', placeholder: 'https://…', hint: 'Webhook URL generated by a Teams workflow.', required: true }],
  discord: [{ key: 'url', label: 'Discord webhook URL', type: 'url', placeholder: 'https://…', required: true }],
  google_chat: [{ key: 'url', label: 'Google Chat webhook URL', type: 'url', placeholder: 'https://…', required: true }],
  telegram: [
    { key: 'bot_token', label: 'Bot token', type: 'password', placeholder: 'Paste bot token', required: true },
    { key: 'chat_id', label: 'Chat ID', placeholder: 'Channel or chat ID', required: true },
  ],
  webhook: [
    { key: 'url', label: 'Webhook URL', type: 'url', placeholder: 'https://events.example.com/sslping', required: true },
    { key: 'signing_secret', label: 'Signing secret', type: 'password', placeholder: 'Generate or paste a signing secret', hint: 'Used to sign request bodies for verification.' },
    { key: 'header_name', label: 'Custom header name', placeholder: 'X-Integration-Key' },
    { key: 'header_value', label: 'Custom header value', type: 'password', placeholder: 'Header value' },
    { key: 'custom_value', label: 'Custom payload value', placeholder: 'Optional routing value' },
  ],
  pagerduty: [{ key: 'routing_key', label: 'Integration routing key', type: 'password', placeholder: 'Paste routing key', required: true }],
  opsgenie: [
    { key: 'api_key', label: 'Opsgenie API key', type: 'password', placeholder: 'Paste API key', required: true },
    { key: 'region', label: 'Region', placeholder: 'us or eu', hint: 'Leave blank to use the US endpoint.' },
  ],
  pushover: [
    { key: 'api_token', label: 'Application API token', type: 'password', placeholder: 'Paste API token', required: true },
    { key: 'user_key', label: 'User or group key', type: 'password', placeholder: 'Paste user key', required: true },
    { key: 'device', label: 'Device', placeholder: 'Optional device name' },
  ],
  pushbullet: [{ key: 'access_token', label: 'Access token', type: 'password', placeholder: 'Paste access token', required: true }],
  email: [{ key: 'recipients', label: 'Recipients', type: 'email', placeholder: 'alerts@example.com', hint: 'Use comma-separated addresses for multiple recipients.', required: true }],
  sms: [
    { key: 'account_sid', label: 'Account SID', type: 'password', placeholder: 'Paste account SID', required: true },
    { key: 'auth_token', label: 'Auth token', type: 'password', placeholder: 'Paste auth token', required: true },
    { key: 'from', label: 'From number', type: 'tel', placeholder: '+15550100100', required: true },
    { key: 'to', label: 'Recipient number', type: 'tel', placeholder: '+15550100200', required: true },
  ],
  voice: [
    { key: 'account_sid', label: 'Account SID', type: 'password', placeholder: 'Paste account SID', required: true },
    { key: 'auth_token', label: 'Auth token', type: 'password', placeholder: 'Paste auth token', required: true },
    { key: 'from', label: 'From number', type: 'tel', placeholder: '+15550100100', required: true },
    { key: 'to', label: 'Recipient number', type: 'tel', placeholder: '+15550100200', required: true },
  ],
}

const eventOptions: readonly { value: IntegrationEvent; label: string; description: string }[] = [
  { value: 'monitor.down', label: 'Down events', description: 'A monitor changes to down.' },
  { value: 'monitor.up', label: 'Up events', description: 'A monitor recovers.' },
  { value: 'monitor.slow', label: 'Slow responses', description: 'Response time crosses its threshold.' },
  { value: 'ssl.expiry', label: 'SSL expiry', description: 'A certificate reaches a warning threshold.' },
  { value: 'domain.expiry', label: 'Domain expiry', description: 'A domain reaches a warning threshold.' },
  { value: 'incident.updated', label: 'Incident updates', description: 'Incident status or timeline changes.' },
  { value: 'maintenance.started', label: 'Maintenance starts', description: 'A scheduled window begins.' },
]

export interface IntegrationFormModalProps {
  open: boolean
  catalog: readonly IntegrationCatalogItem[]
  initialType?: IntegrationType
  integration?: IntegrationViewModel | null
  monitors?: readonly MonitorViewModel[]
  initialMonitorIds?: readonly string[]
  saving?: boolean
  error?: string
  onClose: () => void
  onSubmit: (input: IntegrationInput) => void | Promise<void>
}

export function IntegrationFormModal({
  open,
  catalog,
  initialType = 'slack',
  integration = null,
  monitors = demoMonitors,
  initialMonitorIds = [],
  saving = false,
  error,
  onClose,
  onSubmit,
}: IntegrationFormModalProps) {
  const { t } = useI18n()
  const [name, setName] = useState('')
  const [type, setType] = useState<IntegrationType>(initialType)
  const [active, setActive] = useState(true)
  const [events, setEvents] = useState<readonly IntegrationEvent[]>(['monitor.down', 'monitor.up'])
  const [monitorIds, setMonitorIds] = useState<readonly string[]>([])
  const [config, setConfig] = useState<Readonly<Record<string, string>>>({})
  const [localError, setLocalError] = useState('')

  useEffect(() => {
    if (!open) return
    setName(integration?.name ?? '')
    setType(integration?.type ?? initialType)
    setActive(integration?.active ?? true)
    setEvents(integration?.events ?? ['monitor.down', 'monitor.up'])
    setMonitorIds(integration?.monitorIds ?? initialMonitorIds)
    setConfig({})
    setLocalError('')
  }, [initialMonitorIds, initialType, integration, open])

  const provider = useMemo(() => catalog.find((item) => item.type === type), [catalog, type])
  const fields = providerFields[type]

  const toggleEvent = (value: IntegrationEvent) => {
    setEvents((current) => current.includes(value) ? current.filter((item) => item !== value) : [...current, value])
  }

  const toggleMonitor = (monitorId: string) => {
    setMonitorIds((current) => current.includes(monitorId) ? current.filter((item) => item !== monitorId) : [...current, monitorId])
  }

  const submit = (event: FormEvent) => {
    event.preventDefault()
    if (events.length === 0) {
      setLocalError(t('integrations.form.chooseEvent'))
      return
    }
    if (!integration) {
      const missing = fields.find((field) => field.required && !config[field.key]?.trim())
      if (missing) {
        setLocalError(t('integrations.form.required', { field: translated(`integrations.field.${missing.key}`, missing.label) }))
        return
      }
    }
    setLocalError('')
    void onSubmit({
      name: name.trim(),
      type,
      active,
      events,
      monitorIds,
      config,
    })
  }

  const translated = (key: string, fallback: string) => {
    const value = t(key)
    return value === key ? fallback : value
  }

  const providerFieldLabel = (field: ProviderField) => {
    const label = translated(`integrations.field.${field.key}`, field.label)
    if (field.key !== 'url' || type === 'webhook') return label
    return `${provider?.name ?? field.label.split(' ')[0]} ${label}`
  }

  return (
    <Modal
      open={open}
      onClose={() => !saving && onClose()}
      title={<>{t(integration ? 'integrations.form.edit' : 'integrations.form.add')} <span className="success-text">{provider?.name ?? t('integrations.form.integration')}</span></>}
      icon={<Activity size={39} />}
      width="lg"
    >
      <form onSubmit={submit}>
        <div className="form-section form-grid">
          <Field label={t('integrations.form.name')} hint={t('integrations.form.nameHint')}>
            <input autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder={t('integrations.form.namePlaceholder', { provider: provider?.name ?? t('integrations.form.integration') })} required />
          </Field>
          <Field label={t('integrations.form.provider')}>
            <Select value={type} onChange={(event) => { setType(event.target.value as IntegrationType); setConfig({}) }} disabled={Boolean(integration)}>
              {catalog.filter((item) => item.available).map((item) => <option key={item.type} value={item.type}>{item.name}</option>)}
            </Select>
          </Field>
        </div>

        <div className="form-section">
          <h3 className="form-section__title">{t('integrations.form.providerConfig')}</h3>
          {integration && <p className="account-form-note"><ShieldCheck size={17} /> {t('integrations.form.credentialsHint')}</p>}
          <div className="form-grid integration-provider-fields">
            {fields.map((field) => (
              <Field key={field.key} label={providerFieldLabel(field)} hint={field.hint ? translated(`integrations.field.${field.key}Hint`, field.hint) : undefined}>
                <input
                  type={field.type ?? 'text'}
                  value={config[field.key] ?? ''}
                  onChange={(event) => setConfig((current) => ({ ...current, [field.key]: event.target.value }))}
                  placeholder={integration && field.type === 'password' ? t('integrations.form.keepExisting') : translated(`integrations.field.${field.key}Placeholder`, field.placeholder)}
                  required={!integration && field.required}
                  multiple={field.key === 'recipients'}
                  pattern={field.key === 'from' || field.key === 'to' ? '\\+[0-9]{7,15}' : undefined}
                  autoComplete="off"
                />
              </Field>
            ))}
          </div>
        </div>

        <fieldset className="form-section account-fieldset">
          <legend>{t('integrations.form.events')}</legend>
          <p>{t('integrations.form.eventsHint')}</p>
          <div className="event-grid">
            {eventOptions.map((option) => (
              <label key={option.value} className={events.includes(option.value) ? 'event-option is-selected' : 'event-option'}>
                <input type="checkbox" checked={events.includes(option.value)} onChange={() => toggleEvent(option.value)} />
                <span><strong>{translated(`integrations.event.${option.value}.label`, option.label)}</strong><small>{translated(`integrations.event.${option.value}.description`, option.description)}</small></span>
              </label>
            ))}
          </div>
        </fieldset>

        <fieldset className="form-section account-fieldset">
          <legend>{t('integrations.form.routing')}</legend>
          <p>{t('integrations.form.routingHint')}</p>
          <div className="monitor-route-grid">
            {monitors.map((monitor) => (
              <label key={monitor.id} className={monitorIds.includes(monitor.id) ? 'monitor-route is-selected' : 'monitor-route'}>
                <input type="checkbox" checked={monitorIds.includes(monitor.id)} onChange={() => toggleMonitor(monitor.id)} />
                <span><strong>{monitor.name}</strong><small>{monitor.typeLabel} · {monitor.group}</small></span>
              </label>
            ))}
          </div>
        </fieldset>

        <div className="form-section integration-active-row"><span><BellRing size={20} /><span><strong>{t('integrations.form.active')}</strong><small>{t('integrations.form.activeHint')}</small></span></span><Toggle checked={active} onChange={setActive} label={t('integrations.form.active')} /></div>
        {(localError || error) && <FeedbackBanner tone="error">{localError || error}</FeedbackBanner>}
        <div className="form-actions"><Button variant="secondary" type="button" onClick={onClose} disabled={saving}>{t('common.cancel')}</Button><Button type="submit" disabled={saving}><Plus size={17} />{saving ? t('common.saving') : integration ? t('integrations.form.update') : t('integrations.form.create')}</Button></div>
      </form>
    </Modal>
  )
}
