import type { MonitorStatus, StatusPageLanguage } from '../../api'
import type { PublicStatusCopy } from './i18n'

export type ExtendedStatusPageLanguage = Exclude<StatusPageLanguage, 'en' | 'zh' | 'zh-Hant' | 'hi' | 'es' | 'fr' | 'ar' | 'bn' | 'pt' | 'ru' | 'id'>

type StatusSummary = Record<MonitorStatus, { title: string; description: string }>
type CoreCopy = Partial<Omit<PublicStatusCopy, 'overall'>> & { overall: StatusSummary }

const extendedPublicStatusCore: Record<ExtendedStatusPageLanguage, CoreCopy> = {
  de: {
    loadingStatusPage: 'Statusseite wird geladen', currentStatus: 'Aktueller Status', updated: 'Aktualisiert', overallUptime: 'Gesamtverfügbarkeit', last24Hours: 'Letzte 24 Stunden', services: 'Dienste', operational: 'betriebsbereit', activeIncidents: 'Aktive Vorfälle', publishedUpdates: 'Veröffentlichte Meldungen', liveMonitoring: 'Live-Überwachung', components: 'Komponenten', noComponents: 'Noch keine Komponenten veröffentlicht', noComponentsBody: 'Der Betreiber hat dieser Seite noch keine öffentlichen Monitore hinzugefügt.', latestUpdates: 'Neueste Meldungen', incidentsAndAnnouncements: 'Vorfälle und Ankündigungen', noIncidents: 'Keine Vorfälle gemeldet', noIncidentsBody: 'Es gibt keine veröffentlichten Vorfälle oder Wartungsankündigungen.', lastChecked: 'Zuletzt geprüft', waitingForFirstCheck: 'Warten auf die erste Prüfung', uptime24h: 'Verfügbarkeit (24 Std.)', averageResponseTime: 'Durchschnittliche Antwortzeit', averageShort: 'Durchschnitt', fastest: 'Schnellste', slowest: 'Langsamste', highResponseTime: 'Hohe Antwortzeit', reportProblem: 'Problem melden', selectIssue: 'Problem auswählen', reportNotWorking: 'Funktioniert gar nicht', reportSlow: 'Funktioniert, aber langsam', resolved: 'Behoben', subscribeToUpdates: 'Updates abonnieren', stayInformed: 'Informiert bleiben', subscribe: 'Abonnieren', generated: 'Erstellt', poweredBy: 'Bereitgestellt von', millisecondsShort: 'ms',
    overall: { up: { title: 'Alle Systeme betriebsbereit', description: 'Alle überwachten Dienste antworten normal.' }, down: { title: 'Dienstunterbrechung', description: 'Mindestens ein Dienst ist derzeit nicht erreichbar.' }, degraded: { title: 'Einige Systeme sind beeinträchtigt', description: 'Wir untersuchen die eingeschränkte Leistung.' }, paused: { title: 'Überwachung teilweise pausiert', description: 'Mindestens eine Prüfung ist vorübergehend pausiert.' }, pending: { title: 'Status wird geprüft', description: 'Aktuelle Prüfergebnisse sind noch nicht verfügbar.' } },
  },
  nl: {
    loadingStatusPage: 'Statuspagina laden', currentStatus: 'Huidige status', updated: 'Bijgewerkt', overallUptime: 'Totale beschikbaarheid', last24Hours: 'Afgelopen 24 uur', services: 'Diensten', operational: 'operationeel', activeIncidents: 'Actieve incidenten', publishedUpdates: 'Gepubliceerde updates', liveMonitoring: 'Livebewaking', components: 'onderdelen', noComponents: 'Nog geen onderdelen gepubliceerd', noComponentsBody: 'De eigenaar heeft nog geen openbare monitors toegevoegd.', latestUpdates: 'Laatste updates', incidentsAndAnnouncements: 'Incidenten en aankondigingen', noIncidents: 'Geen incidenten gemeld', noIncidentsBody: 'Er zijn geen gepubliceerde incidenten of onderhoudsmeldingen.', lastChecked: 'Laatst gecontroleerd', waitingForFirstCheck: 'Wachten op de eerste controle', uptime24h: 'Beschikbaarheid 24 uur', averageResponseTime: 'Gemiddelde responstijd', averageShort: 'Gemiddeld', fastest: 'Snelste', slowest: 'Langzaamste', highResponseTime: 'Hoge responstijd', reportProblem: 'Probleem melden', selectIssue: 'Kies het probleem', reportNotWorking: 'Werkt helemaal niet', reportSlow: 'Werkt, maar langzaam', resolved: 'Opgelost', subscribeToUpdates: 'Abonneren op updates', stayInformed: 'Blijf op de hoogte', subscribe: 'Abonneren', generated: 'Gegenereerd', poweredBy: 'Mogelijk gemaakt door', millisecondsShort: 'ms',
    overall: { up: { title: 'Alle systemen operationeel', description: 'Alle bewaakte diensten reageren normaal.' }, down: { title: 'Dienstonderbreking', description: 'Een of meer diensten zijn momenteel niet beschikbaar.' }, degraded: { title: 'Sommige systemen zijn vertraagd', description: 'We onderzoeken de verminderde prestaties.' }, paused: { title: 'Bewaking gedeeltelijk gepauzeerd', description: 'Een of meer controles zijn tijdelijk gepauzeerd.' }, pending: { title: 'Status wordt gecontroleerd', description: 'De nieuwste resultaten zijn nog niet beschikbaar.' } },
  },
  cs: {
    loadingStatusPage: 'Načítání stavové stránky', currentStatus: 'Aktuální stav', updated: 'Aktualizováno', overallUptime: 'Celková dostupnost', last24Hours: 'Posledních 24 hodin', services: 'Služby', operational: 'v provozu', activeIncidents: 'Aktivní incidenty', publishedUpdates: 'Zveřejněné aktualizace', liveMonitoring: 'Živé monitorování', components: 'komponenty', noComponents: 'Zatím nebyly zveřejněny žádné komponenty', latestUpdates: 'Nejnovější aktualizace', incidentsAndAnnouncements: 'Incidenty a oznámení', noIncidents: 'Žádné hlášené incidenty', lastChecked: 'Poslední kontrola', waitingForFirstCheck: 'Čekání na první kontrolu', uptime24h: 'Dostupnost za 24 hodin', averageResponseTime: 'Průměrná doba odezvy', averageShort: 'Průměr', fastest: 'Nejrychlejší', slowest: 'Nejpomalejší', highResponseTime: 'Vysoká doba odezvy', reportProblem: 'Nahlásit problém', selectIssue: 'Vyberte problém', reportNotWorking: 'Vůbec nefunguje', reportSlow: 'Funguje pomalu', resolved: 'Vyřešeno', subscribeToUpdates: 'Odebírat aktualizace', stayInformed: 'Zůstaňte informováni', subscribe: 'Odebírat', generated: 'Vygenerováno', poweredBy: 'Provozuje', millisecondsShort: 'ms',
    overall: { up: { title: 'Všechny systémy jsou v provozu', description: 'Všechny monitorované služby odpovídají normálně.' }, down: { title: 'Výpadek služby', description: 'Jedna nebo více služeb je nedostupná.' }, degraded: { title: 'Některé systémy jsou omezené', description: 'Prověřujeme snížený výkon.' }, paused: { title: 'Monitorování je částečně pozastaveno', description: 'Některé kontroly jsou dočasně pozastavené.' }, pending: { title: 'Stav se ověřuje', description: 'Nejnovější výsledky zatím nejsou k dispozici.' } },
  },
  da: {
    loadingStatusPage: 'Indlæser statusside', currentStatus: 'Aktuel status', updated: 'Opdateret', overallUptime: 'Samlet oppetid', last24Hours: 'Seneste 24 timer', services: 'Tjenester', operational: 'i drift', activeIncidents: 'Aktive hændelser', publishedUpdates: 'Offentliggjorte opdateringer', liveMonitoring: 'Liveovervågning', components: 'komponenter', noComponents: 'Ingen komponenter offentliggjort endnu', latestUpdates: 'Seneste opdateringer', incidentsAndAnnouncements: 'Hændelser og meddelelser', noIncidents: 'Ingen hændelser rapporteret', lastChecked: 'Senest kontrolleret', waitingForFirstCheck: 'Venter på første kontrol', uptime24h: 'Oppetid 24 timer', averageResponseTime: 'Gennemsnitlig svartid', averageShort: 'Gennemsnit', fastest: 'Hurtigste', slowest: 'Langsomste', highResponseTime: 'Høj svartid', reportProblem: 'Rapportér et problem', selectIssue: 'Vælg problemet', reportNotWorking: 'Virker slet ikke', reportSlow: 'Virker, men langsomt', resolved: 'Løst', subscribeToUpdates: 'Abonnér på opdateringer', stayInformed: 'Hold dig orienteret', subscribe: 'Abonnér', generated: 'Genereret', poweredBy: 'Leveret af', millisecondsShort: 'ms',
    overall: { up: { title: 'Alle systemer fungerer', description: 'Alle overvågede tjenester svarer normalt.' }, down: { title: 'Driftsforstyrrelse', description: 'Én eller flere tjenester er ikke tilgængelige.' }, degraded: { title: 'Nogle systemer er ustabile', description: 'Vi undersøger den nedsatte ydeevne.' }, paused: { title: 'Overvågning delvist sat på pause', description: 'Én eller flere kontroller er midlertidigt sat på pause.' }, pending: { title: 'Status kontrolleres', description: 'De seneste resultater er endnu ikke tilgængelige.' } },
  },
  fi: {
    loadingStatusPage: 'Ladataan tilasivua', currentStatus: 'Nykyinen tila', updated: 'Päivitetty', overallUptime: 'Kokonaiskäytettävyys', last24Hours: 'Viimeiset 24 tuntia', services: 'Palvelut', operational: 'toiminnassa', activeIncidents: 'Aktiiviset häiriöt', publishedUpdates: 'Julkaistut päivitykset', liveMonitoring: 'Reaaliaikainen valvonta', components: 'komponenttia', noComponents: 'Komponentteja ei ole vielä julkaistu', latestUpdates: 'Uusimmat päivitykset', incidentsAndAnnouncements: 'Häiriöt ja ilmoitukset', noIncidents: 'Ei ilmoitettuja häiriöitä', lastChecked: 'Viimeksi tarkistettu', waitingForFirstCheck: 'Odotetaan ensimmäistä tarkistusta', uptime24h: 'Käytettävyys 24 h', averageResponseTime: 'Keskimääräinen vasteaika', averageShort: 'Keskiarvo', fastest: 'Nopein', slowest: 'Hitain', highResponseTime: 'Korkea vasteaika', reportProblem: 'Ilmoita ongelmasta', selectIssue: 'Valitse ongelma', reportNotWorking: 'Ei toimi lainkaan', reportSlow: 'Toimii hitaasti', resolved: 'Ratkaistu', subscribeToUpdates: 'Tilaa päivitykset', stayInformed: 'Pysy ajan tasalla', subscribe: 'Tilaa', generated: 'Luotu', poweredBy: 'Palvelun tarjoaa', millisecondsShort: 'ms',
    overall: { up: { title: 'Kaikki järjestelmät toimivat', description: 'Kaikki valvotut palvelut vastaavat normaalisti.' }, down: { title: 'Palvelukatko', description: 'Yksi tai useampi palvelu ei ole saatavilla.' }, degraded: { title: 'Joidenkin järjestelmien suorituskyky on heikentynyt', description: 'Selvitämme heikentynyttä suorituskykyä.' }, paused: { title: 'Valvonta on osittain keskeytetty', description: 'Yksi tai useampi tarkistus on tilapäisesti keskeytetty.' }, pending: { title: 'Tilaa tarkistetaan', description: 'Uusimmat tulokset eivät ole vielä saatavilla.' } },
  },
  el: {
    loadingStatusPage: 'Φόρτωση σελίδας κατάστασης', currentStatus: 'Τρέχουσα κατάσταση', updated: 'Ενημερώθηκε', overallUptime: 'Συνολική διαθεσιμότητα', last24Hours: 'Τελευταίες 24 ώρες', services: 'Υπηρεσίες', operational: 'λειτουργικές', activeIncidents: 'Ενεργά συμβάντα', publishedUpdates: 'Δημοσιευμένες ενημερώσεις', liveMonitoring: 'Ζωντανή παρακολούθηση', components: 'στοιχεία', noComponents: 'Δεν έχουν δημοσιευτεί στοιχεία', latestUpdates: 'Τελευταίες ενημερώσεις', incidentsAndAnnouncements: 'Συμβάντα και ανακοινώσεις', noIncidents: 'Δεν έχουν αναφερθεί συμβάντα', lastChecked: 'Τελευταίος έλεγχος', waitingForFirstCheck: 'Αναμονή πρώτου ελέγχου', uptime24h: 'Διαθεσιμότητα 24 ωρών', averageResponseTime: 'Μέσος χρόνος απόκρισης', averageShort: 'Μέσος', fastest: 'Ταχύτερο', slowest: 'Αργότερο', reportProblem: 'Αναφορά προβλήματος', reportNotWorking: 'Δεν λειτουργεί καθόλου', reportSlow: 'Λειτουργεί αργά', resolved: 'Επιλύθηκε', subscribeToUpdates: 'Εγγραφή στις ενημερώσεις', subscribe: 'Εγγραφή', generated: 'Δημιουργήθηκε', poweredBy: 'Με την υποστήριξη', millisecondsShort: 'ms',
    overall: { up: { title: 'Όλα τα συστήματα λειτουργούν', description: 'Όλες οι παρακολουθούμενες υπηρεσίες ανταποκρίνονται κανονικά.' }, down: { title: 'Διακοπή υπηρεσίας', description: 'Μία ή περισσότερες υπηρεσίες δεν είναι διαθέσιμες.' }, degraded: { title: 'Μερικά συστήματα υπολειτουργούν', description: 'Διερευνούμε τη μειωμένη απόδοση.' }, paused: { title: 'Η παρακολούθηση έχει μερικώς παύσει', description: 'Ορισμένοι έλεγχοι έχουν παύσει προσωρινά.' }, pending: { title: 'Η κατάσταση ελέγχεται', description: 'Τα νεότερα αποτελέσματα δεν είναι ακόμη διαθέσιμα.' } },
  },
  hr: {
    currentStatus: 'Trenutačni status', updated: 'Ažurirano', overallUptime: 'Ukupna dostupnost', last24Hours: 'Posljednja 24 sata', services: 'Usluge', operational: 'operativno', activeIncidents: 'Aktivni incidenti', liveMonitoring: 'Nadzor uživo', latestUpdates: 'Najnovija ažuriranja', noIncidents: 'Nema prijavljenih incidenata', lastChecked: 'Posljednja provjera', waitingForFirstCheck: 'Čekanje prve provjere', uptime24h: 'Dostupnost 24 sata', averageResponseTime: 'Prosječno vrijeme odziva', averageShort: 'Prosjek', fastest: 'Najbrže', slowest: 'Najsporije', reportProblem: 'Prijavi problem', reportNotWorking: 'Uopće ne radi', reportSlow: 'Radi, ali sporo', resolved: 'Riješeno', subscribeToUpdates: 'Pretplati se na ažuriranja', subscribe: 'Pretplati se', generated: 'Generirano', poweredBy: 'Pokreće', millisecondsShort: 'ms',
    overall: { up: { title: 'Svi sustavi rade', description: 'Sve nadzirane usluge odgovaraju normalno.' }, down: { title: 'Prekid usluge', description: 'Jedna ili više usluga trenutačno nije dostupna.' }, degraded: { title: 'Neki sustavi rade otežano', description: 'Istražujemo smanjene performanse.' }, paused: { title: 'Nadzor je djelomično pauziran', description: 'Jedna ili više provjera privremeno je pauzirana.' }, pending: { title: 'Status se provjerava', description: 'Najnoviji rezultati još nisu dostupni.' } },
  },
  hu: {
    currentStatus: 'Jelenlegi állapot', updated: 'Frissítve', overallUptime: 'Teljes rendelkezésre állás', last24Hours: 'Elmúlt 24 óra', services: 'Szolgáltatások', operational: 'működik', activeIncidents: 'Aktív incidensek', liveMonitoring: 'Élő megfigyelés', latestUpdates: 'Legfrissebb frissítések', noIncidents: 'Nincs jelentett incidens', lastChecked: 'Utolsó ellenőrzés', waitingForFirstCheck: 'Várakozás az első ellenőrzésre', uptime24h: '24 órás rendelkezésre állás', averageResponseTime: 'Átlagos válaszidő', averageShort: 'Átlag', fastest: 'Leggyorsabb', slowest: 'Leglassabb', reportProblem: 'Probléma jelentése', reportNotWorking: 'Egyáltalán nem működik', reportSlow: 'Működik, de lassú', resolved: 'Megoldva', subscribeToUpdates: 'Feliratkozás a frissítésekre', subscribe: 'Feliratkozás', generated: 'Létrehozva', poweredBy: 'Működteti', millisecondsShort: 'ms',
    overall: { up: { title: 'Minden rendszer működik', description: 'Minden megfigyelt szolgáltatás megfelelően válaszol.' }, down: { title: 'Szolgáltatáskimaradás', description: 'Egy vagy több szolgáltatás nem érhető el.' }, degraded: { title: 'Néhány rendszer korlátozottan működik', description: 'Vizsgáljuk a csökkent teljesítményt.' }, paused: { title: 'A megfigyelés részben szünetel', description: 'Egy vagy több ellenőrzés ideiglenesen szünetel.' }, pending: { title: 'Az állapot ellenőrzése folyamatban', description: 'A legfrissebb eredmények még nem érhetők el.' } },
  },
  he: {
    currentStatus: 'מצב נוכחי', updated: 'עודכן', overallUptime: 'זמינות כוללת', last24Hours: '24 השעות האחרונות', services: 'שירותים', operational: 'פועלים', activeIncidents: 'תקלות פעילות', liveMonitoring: 'ניטור בזמן אמת', latestUpdates: 'עדכונים אחרונים', noIncidents: 'לא דווחו תקלות', lastChecked: 'נבדק לאחרונה', waitingForFirstCheck: 'ממתין לבדיקה הראשונה', uptime24h: 'זמינות ב־24 שעות', averageResponseTime: 'זמן תגובה ממוצע', averageShort: 'ממוצע', fastest: 'המהיר ביותר', slowest: 'האיטי ביותר', reportProblem: 'דיווח על בעיה', reportNotWorking: 'לא פועל כלל', reportSlow: 'פועל לאט', resolved: 'נפתר', subscribeToUpdates: 'הרשמה לעדכונים', subscribe: 'הרשמה', generated: 'נוצר', poweredBy: 'מופעל על ידי', millisecondsShort: 'אלפיות שנייה',
    overall: { up: { title: 'כל המערכות פועלות', description: 'כל השירותים המנוטרים מגיבים כרגיל.' }, down: { title: 'הפרעה בשירות', description: 'שירות אחד או יותר אינם זמינים.' }, degraded: { title: 'חלק מהמערכות מושפעות', description: 'אנו בודקים את הירידה בביצועים.' }, paused: { title: 'הניטור הושהה חלקית', description: 'בדיקה אחת או יותר הושהתה זמנית.' }, pending: { title: 'המצב נבדק', description: 'תוצאות הניטור האחרונות עדיין אינן זמינות.' } },
  },
  it: {
    currentStatus: 'Stato attuale', updated: 'Aggiornato', overallUptime: 'Disponibilità complessiva', last24Hours: 'Ultime 24 ore', services: 'Servizi', operational: 'operativi', activeIncidents: 'Incidenti attivi', liveMonitoring: 'Monitoraggio in tempo reale', latestUpdates: 'Ultimi aggiornamenti', noIncidents: 'Nessun incidente segnalato', lastChecked: 'Ultimo controllo', waitingForFirstCheck: 'In attesa del primo controllo', uptime24h: 'Disponibilità 24 ore', averageResponseTime: 'Tempo medio di risposta', averageShort: 'Media', fastest: 'Più veloce', slowest: 'Più lento', reportProblem: 'Segnala un problema', reportNotWorking: 'Non funziona affatto', reportSlow: 'Funziona, ma lentamente', resolved: 'Risolto', subscribeToUpdates: 'Iscriviti agli aggiornamenti', subscribe: 'Iscriviti', generated: 'Generato', poweredBy: 'Offerto da', millisecondsShort: 'ms',
    overall: { up: { title: 'Tutti i sistemi sono operativi', description: 'Tutti i servizi monitorati rispondono normalmente.' }, down: { title: 'Interruzione del servizio', description: 'Uno o più servizi non sono disponibili.' }, degraded: { title: 'Alcuni sistemi sono degradati', description: 'Stiamo verificando le prestazioni ridotte.' }, paused: { title: 'Monitoraggio parzialmente in pausa', description: 'Uno o più controlli sono temporaneamente in pausa.' }, pending: { title: 'Verifica dello stato in corso', description: 'Gli ultimi risultati non sono ancora disponibili.' } },
  },
  ja: {
    currentStatus: '現在のステータス', updated: '更新', overallUptime: '総合稼働率', last24Hours: '過去24時間', services: 'サービス', operational: '正常稼働', activeIncidents: '発生中の障害', liveMonitoring: 'リアルタイム監視', latestUpdates: '最新情報', noIncidents: '障害は報告されていません', lastChecked: '最終確認', waitingForFirstCheck: '最初の確認を待っています', uptime24h: '24時間の稼働率', averageResponseTime: '平均応答時間', averageShort: '平均', fastest: '最速', slowest: '最遅', reportProblem: '問題を報告', reportNotWorking: '全く動作しない', reportSlow: '動作するが遅い', resolved: '解決済み', subscribeToUpdates: '更新情報を購読', subscribe: '購読', generated: '生成', poweredBy: '提供', millisecondsShort: 'ms',
    overall: { up: { title: 'すべてのシステムが正常です', description: '監視中のすべてのサービスが正常に応答しています。' }, down: { title: 'サービス障害', description: '1つ以上のサービスを利用できません。' }, degraded: { title: '一部のシステムのパフォーマンスが低下しています', description: 'パフォーマンス低下を調査中です。' }, paused: { title: '監視が一部停止中です', description: '1つ以上のチェックが一時停止されています。' }, pending: { title: 'ステータスを確認中です', description: '最新の監視結果はまだ利用できません。' } },
  },
  ms: {
    currentStatus: 'Status semasa', updated: 'Dikemas kini', overallUptime: 'Ketersediaan keseluruhan', last24Hours: '24 jam lalu', services: 'Perkhidmatan', operational: 'beroperasi', activeIncidents: 'Insiden aktif', liveMonitoring: 'Pemantauan langsung', latestUpdates: 'Kemas kini terkini', noIncidents: 'Tiada insiden dilaporkan', lastChecked: 'Terakhir diperiksa', waitingForFirstCheck: 'Menunggu pemeriksaan pertama', uptime24h: 'Ketersediaan 24 jam', averageResponseTime: 'Purata masa respons', averageShort: 'Purata', fastest: 'Terpantas', slowest: 'Paling perlahan', reportProblem: 'Laporkan masalah', reportNotWorking: 'Tidak berfungsi langsung', reportSlow: 'Berfungsi tetapi perlahan', resolved: 'Selesai', subscribeToUpdates: 'Langgan kemas kini', subscribe: 'Langgan', generated: 'Dijana', poweredBy: 'Dikuasakan oleh', millisecondsShort: 'ms',
    overall: { up: { title: 'Semua sistem beroperasi', description: 'Semua perkhidmatan yang dipantau bertindak balas seperti biasa.' }, down: { title: 'Gangguan perkhidmatan', description: 'Satu atau lebih perkhidmatan tidak tersedia.' }, degraded: { title: 'Sesetengah sistem terjejas', description: 'Kami sedang menyiasat prestasi yang berkurangan.' }, paused: { title: 'Pemantauan dijeda sebahagian', description: 'Satu atau lebih pemeriksaan dijeda sementara.' }, pending: { title: 'Status sedang disahkan', description: 'Hasil pemantauan terkini belum tersedia.' } },
  },
  no: {
    loadingStatusPage: 'Laster statusside', currentStatus: 'Nåværende status', updated: 'Oppdatert', overallUptime: 'Samlet oppetid', last24Hours: 'Siste 24 timer', services: 'Tjenester', operational: 'i drift', activeIncidents: 'Aktive hendelser', liveMonitoring: 'Liveovervåking', latestUpdates: 'Siste oppdateringer', noIncidents: 'Ingen hendelser rapportert', lastChecked: 'Sist kontrollert', waitingForFirstCheck: 'Venter på første kontroll', uptime24h: 'Oppetid 24 timer', averageResponseTime: 'Gjennomsnittlig responstid', averageShort: 'Gjennomsnitt', fastest: 'Raskest', slowest: 'Tregest', reportProblem: 'Rapporter et problem', reportNotWorking: 'Fungerer ikke i det hele tatt', reportSlow: 'Fungerer, men langsomt', resolved: 'Løst', subscribeToUpdates: 'Abonner på oppdateringer', subscribe: 'Abonner', generated: 'Generert', poweredBy: 'Levert av', millisecondsShort: 'ms',
    overall: { up: { title: 'Alle systemer fungerer', description: 'Alle overvåkede tjenester svarer normalt.' }, down: { title: 'Driftsavbrudd', description: 'Én eller flere tjenester er utilgjengelige.' }, degraded: { title: 'Noen systemer er ustabile', description: 'Vi undersøker redusert ytelse.' }, paused: { title: 'Overvåking delvis pauset', description: 'Én eller flere kontroller er midlertidig pauset.' }, pending: { title: 'Status kontrolleres', description: 'De nyeste resultatene er ikke tilgjengelige ennå.' } },
  },
  fil: {
    currentStatus: 'Kasalukuyang status', updated: 'Na-update', overallUptime: 'Kabuuang availability', last24Hours: 'Nakalipas na 24 oras', services: 'Mga serbisyo', operational: 'gumagana', activeIncidents: 'Mga aktibong insidente', liveMonitoring: 'Live monitoring', latestUpdates: 'Mga pinakabagong update', noIncidents: 'Walang naiulat na insidente', lastChecked: 'Huling sinuri', waitingForFirstCheck: 'Naghihintay sa unang pagsusuri', uptime24h: '24-oras na availability', averageResponseTime: 'Karaniwang oras ng tugon', averageShort: 'Karaniwan', fastest: 'Pinakamabilis', slowest: 'Pinakamabagal', reportProblem: 'Mag-ulat ng problema', reportNotWorking: 'Hindi talaga gumagana', reportSlow: 'Gumagana pero mabagal', resolved: 'Nalutas', subscribeToUpdates: 'Mag-subscribe sa mga update', subscribe: 'Mag-subscribe', generated: 'Nabuo', poweredBy: 'Pinapagana ng', millisecondsShort: 'ms',
    overall: { up: { title: 'Gumagana ang lahat ng system', description: 'Normal na tumutugon ang lahat ng minomonitor na serbisyo.' }, down: { title: 'Pagkaantala ng serbisyo', description: 'Hindi available ang isa o higit pang serbisyo.' }, degraded: { title: 'May problema ang ilang system', description: 'Sinisiyasat namin ang mababang performance.' }, paused: { title: 'Bahagyang naka-pause ang monitoring', description: 'Pansamantalang naka-pause ang isa o higit pang pagsusuri.' }, pending: { title: 'Sinusuri ang status', description: 'Hindi pa available ang pinakabagong resulta.' } },
  },
  ur: {
    currentStatus: 'موجودہ حالت', updated: 'اپ ڈیٹ شدہ', overallUptime: 'مجموعی دستیابی', last24Hours: 'گزشتہ 24 گھنٹے', services: 'خدمات', operational: 'فعال', activeIncidents: 'فعال واقعات', liveMonitoring: 'براہ راست نگرانی', latestUpdates: 'تازہ ترین اپ ڈیٹس', noIncidents: 'کوئی واقعہ رپورٹ نہیں ہوا', lastChecked: 'آخری جانچ', waitingForFirstCheck: 'پہلی جانچ کا انتظار', uptime24h: '24 گھنٹے کی دستیابی', averageResponseTime: 'اوسط جوابی وقت', averageShort: 'اوسط', fastest: 'تیز ترین', slowest: 'سست ترین', reportProblem: 'مسئلہ رپورٹ کریں', reportNotWorking: 'بالکل کام نہیں کر رہا', reportSlow: 'کام کر رہا ہے لیکن آہستہ', resolved: 'حل شدہ', subscribeToUpdates: 'اپ ڈیٹس سبسکرائب کریں', subscribe: 'سبسکرائب', generated: 'تیار شدہ', poweredBy: 'پیشکش', millisecondsShort: 'ملی سیکنڈ',
    overall: { up: { title: 'تمام نظام فعال ہیں', description: 'تمام نگرانی شدہ خدمات معمول کے مطابق جواب دے رہی ہیں۔' }, down: { title: 'سروس میں رکاوٹ', description: 'ایک یا زیادہ خدمات دستیاب نہیں ہیں۔' }, degraded: { title: 'کچھ نظام متاثر ہیں', description: 'ہم کم کارکردگی کی جانچ کر رہے ہیں۔' }, paused: { title: 'نگرانی جزوی طور پر روکی گئی ہے', description: 'ایک یا زیادہ جانچیں عارضی طور پر روکی گئی ہیں۔' }, pending: { title: 'حالت کی جانچ جاری ہے', description: 'تازہ ترین نتائج ابھی دستیاب نہیں۔' } },
  },
  pl: {
    currentStatus: 'Aktualny status', updated: 'Zaktualizowano', overallUptime: 'Ogólna dostępność', last24Hours: 'Ostatnie 24 godziny', services: 'Usługi', operational: 'działają', activeIncidents: 'Aktywne awarie', liveMonitoring: 'Monitoring na żywo', latestUpdates: 'Najnowsze aktualizacje', noIncidents: 'Brak zgłoszonych awarii', lastChecked: 'Ostatnie sprawdzenie', waitingForFirstCheck: 'Oczekiwanie na pierwsze sprawdzenie', uptime24h: 'Dostępność 24 h', averageResponseTime: 'Średni czas odpowiedzi', averageShort: 'Średnia', fastest: 'Najszybszy', slowest: 'Najwolniejszy', reportProblem: 'Zgłoś problem', reportNotWorking: 'Nie działa w ogóle', reportSlow: 'Działa, ale wolno', resolved: 'Rozwiązano', subscribeToUpdates: 'Subskrybuj aktualizacje', subscribe: 'Subskrybuj', generated: 'Wygenerowano', poweredBy: 'Obsługiwane przez', millisecondsShort: 'ms',
    overall: { up: { title: 'Wszystkie systemy działają', description: 'Wszystkie monitorowane usługi odpowiadają prawidłowo.' }, down: { title: 'Przerwa w działaniu usługi', description: 'Co najmniej jedna usługa jest niedostępna.' }, degraded: { title: 'Niektóre systemy działają gorzej', description: 'Badamy obniżoną wydajność.' }, paused: { title: 'Monitoring częściowo wstrzymany', description: 'Co najmniej jedno sprawdzenie jest tymczasowo wstrzymane.' }, pending: { title: 'Status jest sprawdzany', description: 'Najnowsze wyniki nie są jeszcze dostępne.' } },
  },
  ro: {
    currentStatus: 'Stare curentă', updated: 'Actualizat', overallUptime: 'Disponibilitate generală', last24Hours: 'Ultimele 24 de ore', services: 'Servicii', operational: 'operaționale', activeIncidents: 'Incidente active', liveMonitoring: 'Monitorizare în timp real', latestUpdates: 'Ultimele actualizări', noIncidents: 'Niciun incident raportat', lastChecked: 'Ultima verificare', waitingForFirstCheck: 'Se așteaptă prima verificare', uptime24h: 'Disponibilitate 24 de ore', averageResponseTime: 'Timp mediu de răspuns', averageShort: 'Medie', fastest: 'Cel mai rapid', slowest: 'Cel mai lent', reportProblem: 'Raportează o problemă', reportNotWorking: 'Nu funcționează deloc', reportSlow: 'Funcționează lent', resolved: 'Rezolvat', subscribeToUpdates: 'Abonează-te la actualizări', subscribe: 'Abonează-te', generated: 'Generat', poweredBy: 'Oferit de', millisecondsShort: 'ms',
    overall: { up: { title: 'Toate sistemele sunt operaționale', description: 'Toate serviciile monitorizate răspund normal.' }, down: { title: 'Întrerupere de serviciu', description: 'Unul sau mai multe servicii nu sunt disponibile.' }, degraded: { title: 'Unele sisteme sunt degradate', description: 'Investigăm performanța redusă.' }, paused: { title: 'Monitorizare parțial suspendată', description: 'Una sau mai multe verificări sunt suspendate temporar.' }, pending: { title: 'Starea este verificată', description: 'Cele mai noi rezultate nu sunt încă disponibile.' } },
  },
  sr: {
    currentStatus: 'Тренутни статус', updated: 'Ажурирано', overallUptime: 'Укупна доступност', last24Hours: 'Последња 24 сата', services: 'Услуге', operational: 'раде', activeIncidents: 'Активни инциденти', liveMonitoring: 'Надзор уживо', latestUpdates: 'Најновија ажурирања', noIncidents: 'Нема пријављених инцидената', lastChecked: 'Последња провера', waitingForFirstCheck: 'Чекање прве провере', uptime24h: 'Доступност 24 сата', averageResponseTime: 'Просечно време одзива', averageShort: 'Просек', fastest: 'Најбрже', slowest: 'Најспорије', reportProblem: 'Пријави проблем', reportNotWorking: 'Уопште не ради', reportSlow: 'Ради, али споро', resolved: 'Решено', subscribeToUpdates: 'Прати ажурирања', subscribe: 'Прати', generated: 'Генерисано', poweredBy: 'Покреће', millisecondsShort: 'ms',
    overall: { up: { title: 'Сви системи раде', description: 'Све надзиране услуге одговарају нормално.' }, down: { title: 'Прекид услуге', description: 'Једна или више услуга није доступна.' }, degraded: { title: 'Неки системи раде отежано', description: 'Истражујемо смањене перформансе.' }, paused: { title: 'Надзор је делимично паузиран', description: 'Једна или више провера је привремено паузирана.' }, pending: { title: 'Статус се проверава', description: 'Најновији резултати још нису доступни.' } },
  },
  sv: {
    currentStatus: 'Aktuell status', updated: 'Uppdaterad', overallUptime: 'Total tillgänglighet', last24Hours: 'Senaste 24 timmarna', services: 'Tjänster', operational: 'i drift', activeIncidents: 'Aktiva incidenter', liveMonitoring: 'Liveövervakning', latestUpdates: 'Senaste uppdateringarna', noIncidents: 'Inga incidenter rapporterade', lastChecked: 'Senast kontrollerad', waitingForFirstCheck: 'Väntar på den första kontrollen', uptime24h: 'Tillgänglighet 24 timmar', averageResponseTime: 'Genomsnittlig svarstid', averageShort: 'Genomsnitt', fastest: 'Snabbast', slowest: 'Långsammast', reportProblem: 'Rapportera ett problem', reportNotWorking: 'Fungerar inte alls', reportSlow: 'Fungerar, men långsamt', resolved: 'Löst', subscribeToUpdates: 'Prenumerera på uppdateringar', subscribe: 'Prenumerera', generated: 'Genererad', poweredBy: 'Drivs av', millisecondsShort: 'ms',
    overall: { up: { title: 'Alla system fungerar', description: 'Alla övervakade tjänster svarar normalt.' }, down: { title: 'Tjänsteavbrott', description: 'En eller flera tjänster är inte tillgängliga.' }, degraded: { title: 'Vissa system har nedsatt prestanda', description: 'Vi undersöker den nedsatta prestandan.' }, paused: { title: 'Övervakningen är delvis pausad', description: 'En eller flera kontroller är tillfälligt pausade.' }, pending: { title: 'Status verifieras', description: 'De senaste resultaten är ännu inte tillgängliga.' } },
  },
  sl: {
    currentStatus: 'Trenutno stanje', updated: 'Posodobljeno', overallUptime: 'Skupna razpoložljivost', last24Hours: 'Zadnjih 24 ur', services: 'Storitve', operational: 'delujejo', activeIncidents: 'Aktivni incidenti', liveMonitoring: 'Spremljanje v živo', latestUpdates: 'Najnovejše posodobitve', noIncidents: 'Ni prijavljenih incidentov', lastChecked: 'Zadnji pregled', waitingForFirstCheck: 'Čakanje na prvi pregled', uptime24h: 'Razpoložljivost 24 ur', averageResponseTime: 'Povprečni odzivni čas', averageShort: 'Povprečje', fastest: 'Najhitreje', slowest: 'Najpočasneje', reportProblem: 'Prijavi težavo', reportNotWorking: 'Sploh ne deluje', reportSlow: 'Deluje, vendar počasi', resolved: 'Rešeno', subscribeToUpdates: 'Naroči se na posodobitve', subscribe: 'Naroči se', generated: 'Ustvarjeno', poweredBy: 'Poganja', millisecondsShort: 'ms',
    overall: { up: { title: 'Vsi sistemi delujejo', description: 'Vse spremljane storitve se odzivajo običajno.' }, down: { title: 'Prekinitev storitve', description: 'Ena ali več storitev ni na voljo.' }, degraded: { title: 'Nekateri sistemi delujejo okrnjeno', description: 'Preiskujemo zmanjšano zmogljivost.' }, paused: { title: 'Spremljanje je delno zaustavljeno', description: 'En ali več pregledov je začasno zaustavljenih.' }, pending: { title: 'Stanje se preverja', description: 'Najnovejši rezultati še niso na voljo.' } },
  },
  sk: {
    currentStatus: 'Aktuálny stav', updated: 'Aktualizované', overallUptime: 'Celková dostupnosť', last24Hours: 'Posledných 24 hodín', services: 'Služby', operational: 'v prevádzke', activeIncidents: 'Aktívne incidenty', liveMonitoring: 'Živé monitorovanie', latestUpdates: 'Najnovšie aktualizácie', noIncidents: 'Žiadne hlásené incidenty', lastChecked: 'Posledná kontrola', waitingForFirstCheck: 'Čakanie na prvú kontrolu', uptime24h: 'Dostupnosť 24 hodín', averageResponseTime: 'Priemerný čas odozvy', averageShort: 'Priemer', fastest: 'Najrýchlejšie', slowest: 'Najpomalšie', reportProblem: 'Nahlásiť problém', reportNotWorking: 'Vôbec nefunguje', reportSlow: 'Funguje pomaly', resolved: 'Vyriešené', subscribeToUpdates: 'Odoberať aktualizácie', subscribe: 'Odoberať', generated: 'Vygenerované', poweredBy: 'Prevádzkuje', millisecondsShort: 'ms',
    overall: { up: { title: 'Všetky systémy sú v prevádzke', description: 'Všetky monitorované služby odpovedajú normálne.' }, down: { title: 'Výpadok služby', description: 'Jedna alebo viac služieb nie je dostupná.' }, degraded: { title: 'Niektoré systémy majú obmedzenú prevádzku', description: 'Preverujeme znížený výkon.' }, paused: { title: 'Monitorovanie je čiastočne pozastavené', description: 'Jedna alebo viac kontrol je dočasne pozastavená.' }, pending: { title: 'Stav sa overuje', description: 'Najnovšie výsledky zatiaľ nie sú k dispozícii.' } },
  },
  tr: {
    currentStatus: 'Güncel durum', updated: 'Güncellendi', overallUptime: 'Genel erişilebilirlik', last24Hours: 'Son 24 saat', services: 'Hizmetler', operational: 'çalışıyor', activeIncidents: 'Aktif olaylar', liveMonitoring: 'Canlı izleme', latestUpdates: 'Son güncellemeler', noIncidents: 'Bildirilen olay yok', lastChecked: 'Son kontrol', waitingForFirstCheck: 'İlk kontrol bekleniyor', uptime24h: '24 saatlik erişilebilirlik', averageResponseTime: 'Ortalama yanıt süresi', averageShort: 'Ortalama', fastest: 'En hızlı', slowest: 'En yavaş', reportProblem: 'Sorun bildir', reportNotWorking: 'Hiç çalışmıyor', reportSlow: 'Çalışıyor ancak yavaş', resolved: 'Çözüldü', subscribeToUpdates: 'Güncellemelere abone ol', subscribe: 'Abone ol', generated: 'Oluşturuldu', poweredBy: 'Sağlayan', millisecondsShort: 'ms',
    overall: { up: { title: 'Tüm sistemler çalışıyor', description: 'İzlenen tüm hizmetler normal yanıt veriyor.' }, down: { title: 'Hizmet kesintisi', description: 'Bir veya daha fazla hizmet kullanılamıyor.' }, degraded: { title: 'Bazı sistemlerin performansı düşük', description: 'Düşük performansı araştırıyoruz.' }, paused: { title: 'İzleme kısmen duraklatıldı', description: 'Bir veya daha fazla kontrol geçici olarak duraklatıldı.' }, pending: { title: 'Durum doğrulanıyor', description: 'En son sonuçlar henüz kullanılamıyor.' } },
  },
  uk: {
    currentStatus: 'Поточний стан', updated: 'Оновлено', overallUptime: 'Загальна доступність', last24Hours: 'Останні 24 години', services: 'Сервіси', operational: 'працюють', activeIncidents: 'Активні інциденти', liveMonitoring: 'Моніторинг у реальному часі', latestUpdates: 'Останні оновлення', noIncidents: 'Інцидентів не зафіксовано', lastChecked: 'Остання перевірка', waitingForFirstCheck: 'Очікування першої перевірки', uptime24h: 'Доступність за 24 години', averageResponseTime: 'Середній час відповіді', averageShort: 'Середнє', fastest: 'Найшвидше', slowest: 'Найповільніше', reportProblem: 'Повідомити про проблему', reportNotWorking: 'Зовсім не працює', reportSlow: 'Працює, але повільно', resolved: 'Вирішено', subscribeToUpdates: 'Підписатися на оновлення', subscribe: 'Підписатися', generated: 'Створено', poweredBy: 'Працює на', millisecondsShort: 'мс',
    overall: { up: { title: 'Усі системи працюють', description: 'Усі сервіси під наглядом відповідають штатно.' }, down: { title: 'Збій у роботі сервісу', description: 'Один або кілька сервісів зараз недоступні.' }, degraded: { title: 'Деякі системи працюють нестабільно', description: 'Ми досліджуємо зниження продуктивності.' }, paused: { title: 'Моніторинг частково призупинено', description: 'Одну або кілька перевірок тимчасово призупинено.' }, pending: { title: 'Стан перевіряється', description: 'Найсвіжіші результати ще недоступні.' } },
  },
}

interface SupplementalCopy {
  loading: string
  notFound: string
  unavailable: string
  retry: string
  goTo: string
  close: string
  follow: string
  thanks: string
  duplicate: string
  processing: string
  privacy: string
  privacyBody: string
  cookies: string
  cookiesBody: string
  password: string
  passwordBody: string
  email: string
  emailBody: string
  consent: string
  done: string
}

const supplementalCopy: Record<ExtendedStatusPageLanguage, SupplementalCopy> = {
  de: { loading: 'Statusseite wird geladen', notFound: 'Statusseite nicht gefunden', unavailable: 'Status derzeit nicht verfügbar.', retry: 'Bitte erneut versuchen.', goTo: 'Zu SSLPing', close: 'Schließen', follow: 'Folgen', thanks: 'Vielen Dank für Ihre Meldung.', duplicate: 'Diese Meldung wurde kürzlich bereits empfangen.', processing: 'Wird verarbeitet…', privacy: 'Datenschutz', privacyBody: 'Diese Seite verarbeitet nur notwendige Daten zum Anzeigen des Dienststatus.', cookies: 'Cookies', cookiesBody: 'Notwendige Speicherung merkt sich Ihre Einstellungen; optionale Analysen nur mit Zustimmung.', password: 'Passwortgeschützte Statusseite', passwordBody: 'Geben Sie das Passwort ein, um Status und Vorfälle anzuzeigen.', email: 'E-Mail-Updates', emailBody: 'Bestätigen Sie Ihre E-Mail-Adresse, um Statusmeldungen zu erhalten.', consent: 'Ich stimme der Verarbeitung für diese Funktion zu.', done: 'Fertig' },
  nl: { loading: 'Statuspagina laden', notFound: 'Statuspagina niet gevonden', unavailable: 'Status tijdelijk niet beschikbaar.', retry: 'Probeer het opnieuw.', goTo: 'Naar SSLPing', close: 'Sluiten', follow: 'Volgen', thanks: 'Bedankt voor uw melding.', duplicate: 'Deze melding is onlangs al ontvangen.', processing: 'Bezig met verwerken…', privacy: 'Privacy', privacyBody: 'Deze pagina verwerkt alleen noodzakelijke gegevens om de servicestatus te tonen.', cookies: 'Cookies', cookiesBody: 'Noodzakelijke opslag onthoudt uw keuze; optionele analyse alleen met toestemming.', password: 'Statuspagina met wachtwoord', passwordBody: 'Voer het wachtwoord in om status en incidenten te bekijken.', email: 'E-mailupdates', emailBody: 'Bevestig uw e-mailadres om statusmeldingen te ontvangen.', consent: 'Ik ga akkoord met de verwerking voor deze functie.', done: 'Gereed' },
  cs: { loading: 'Načítání stavové stránky', notFound: 'Stavová stránka nebyla nalezena', unavailable: 'Stav nyní není dostupný.', retry: 'Zkuste to znovu.', goTo: 'Přejít na SSLPing', close: 'Zavřít', follow: 'Sledovat', thanks: 'Děkujeme za hlášení.', duplicate: 'Toto hlášení jsme nedávno přijali.', processing: 'Zpracovává se…', privacy: 'Soukromí', privacyBody: 'Tato stránka zpracovává pouze údaje nutné k zobrazení stavu služby.', cookies: 'Soubory cookie', cookiesBody: 'Nezbytné úložiště si pamatuje vaši volbu; volitelná analytika jen se souhlasem.', password: 'Stavová stránka chráněná heslem', passwordBody: 'Zadejte heslo pro zobrazení stavu a incidentů.', email: 'E-mailové aktualizace', emailBody: 'Potvrďte e-mailovou adresu pro příjem stavových oznámení.', consent: 'Souhlasím se zpracováním pro tuto funkci.', done: 'Hotovo' },
  da: { loading: 'Indlæser statusside', notFound: 'Statussiden blev ikke fundet', unavailable: 'Status er midlertidigt utilgængelig.', retry: 'Prøv igen.', goTo: 'Gå til SSLPing', close: 'Luk', follow: 'Følg', thanks: 'Tak for din rapport.', duplicate: 'Denne rapport er allerede modtaget for nylig.', processing: 'Behandler…', privacy: 'Privatliv', privacyBody: 'Denne side behandler kun nødvendige data for at vise tjenestens status.', cookies: 'Cookies', cookiesBody: 'Nødvendig lagring husker dit valg; valgfri analyse kun med samtykke.', password: 'Adgangskodebeskyttet statusside', passwordBody: 'Indtast adgangskoden for at se status og hændelser.', email: 'E-mailopdateringer', emailBody: 'Bekræft din e-mailadresse for at modtage statusmeddelelser.', consent: 'Jeg accepterer behandlingen for denne funktion.', done: 'Færdig' },
  fi: { loading: 'Ladataan tilasivua', notFound: 'Tilasivua ei löytynyt', unavailable: 'Tila ei ole juuri nyt saatavilla.', retry: 'Yritä uudelleen.', goTo: 'Siirry SSLPingiin', close: 'Sulje', follow: 'Seuraa', thanks: 'Kiitos ilmoituksesta.', duplicate: 'Tämä ilmoitus on vastaanotettu äskettäin.', processing: 'Käsitellään…', privacy: 'Tietosuoja', privacyBody: 'Tämä sivu käsittelee vain palvelun tilan näyttämiseen tarvittavia tietoja.', cookies: 'Evästeet', cookiesBody: 'Välttämätön tallennus muistaa valintasi; valinnainen analytiikka vain suostumuksella.', password: 'Salasanalla suojattu tilasivu', passwordBody: 'Anna salasana nähdäksesi tilan ja häiriöt.', email: 'Sähköpostipäivitykset', emailBody: 'Vahvista sähköpostiosoitteesi saadaksesi tilailmoituksia.', consent: 'Hyväksyn tämän toiminnon edellyttämän käsittelyn.', done: 'Valmis' },
  el: { loading: 'Φόρτωση σελίδας κατάστασης', notFound: 'Η σελίδα κατάστασης δεν βρέθηκε', unavailable: 'Η κατάσταση δεν είναι διαθέσιμη αυτή τη στιγμή.', retry: 'Δοκιμάστε ξανά.', goTo: 'Μετάβαση στο SSLPing', close: 'Κλείσιμο', follow: 'Παρακολούθηση', thanks: 'Ευχαριστούμε για την αναφορά.', duplicate: 'Αυτή η αναφορά έχει ήδη ληφθεί πρόσφατα.', processing: 'Επεξεργασία…', privacy: 'Απόρρητο', privacyBody: 'Αυτή η σελίδα επεξεργάζεται μόνο τα απαραίτητα δεδομένα για την εμφάνιση της κατάστασης.', cookies: 'Cookies', cookiesBody: 'Η απαραίτητη αποθήκευση θυμάται την επιλογή σας· προαιρετικά αναλυτικά μόνο με συγκατάθεση.', password: 'Σελίδα κατάστασης με κωδικό', passwordBody: 'Εισαγάγετε τον κωδικό για να δείτε κατάσταση και συμβάντα.', email: 'Ενημερώσεις email', emailBody: 'Επιβεβαιώστε το email σας για να λαμβάνετε ενημερώσεις κατάστασης.', consent: 'Συμφωνώ με την επεξεργασία για αυτή τη λειτουργία.', done: 'Τέλος' },
  hr: { loading: 'Učitavanje stranice statusa', notFound: 'Stranica statusa nije pronađena', unavailable: 'Status trenutačno nije dostupan.', retry: 'Pokušajte ponovno.', goTo: 'Idi na SSLPing', close: 'Zatvori', follow: 'Prati', thanks: 'Hvala na prijavi.', duplicate: 'Ova je prijava nedavno već zaprimljena.', processing: 'Obrada…', privacy: 'Privatnost', privacyBody: 'Ova stranica obrađuje samo podatke potrebne za prikaz statusa usluge.', cookies: 'Kolačići', cookiesBody: 'Nužna pohrana pamti vaš izbor; neobavezna analitika samo uz privolu.', password: 'Stranica statusa zaštićena lozinkom', passwordBody: 'Unesite lozinku za prikaz statusa i incidenata.', email: 'Ažuriranja e-poštom', emailBody: 'Potvrdite adresu e-pošte za primanje obavijesti.', consent: 'Pristajem na obradu za ovu funkciju.', done: 'Gotovo' },
  hu: { loading: 'Állapotoldal betöltése', notFound: 'Az állapotoldal nem található', unavailable: 'Az állapot jelenleg nem érhető el.', retry: 'Próbálja újra.', goTo: 'Ugrás az SSLPingre', close: 'Bezárás', follow: 'Követés', thanks: 'Köszönjük a jelentést.', duplicate: 'Ezt a jelentést nemrég már megkaptuk.', processing: 'Feldolgozás…', privacy: 'Adatvédelem', privacyBody: 'Ez az oldal csak a szolgáltatás állapotának megjelenítéséhez szükséges adatokat kezeli.', cookies: 'Cookie-k', cookiesBody: 'A szükséges tárolás megjegyzi a választását; opcionális elemzés csak hozzájárulással.', password: 'Jelszóval védett állapotoldal', passwordBody: 'Adja meg a jelszót az állapot és incidensek megtekintéséhez.', email: 'E-mailes frissítések', emailBody: 'Erősítse meg e-mail-címét az állapotértesítésekhez.', consent: 'Hozzájárulok a funkcióhoz szükséges adatkezeléshez.', done: 'Kész' },
  he: { loading: 'טוען דף סטטוס', notFound: 'דף הסטטוס לא נמצא', unavailable: 'הסטטוס אינו זמין כרגע.', retry: 'נסו שוב.', goTo: 'מעבר ל-SSLPing', close: 'סגירה', follow: 'מעקב', thanks: 'תודה על הדיווח.', duplicate: 'דיווח זה כבר התקבל לאחרונה.', processing: 'בעיבוד…', privacy: 'פרטיות', privacyBody: 'דף זה מעבד רק מידע הנחוץ להצגת מצב השירות.', cookies: 'קובצי Cookie', cookiesBody: 'אחסון חיוני זוכר את הבחירה; ניתוח אופציונלי רק בהסכמה.', password: 'דף סטטוס מוגן בסיסמה', passwordBody: 'הזינו סיסמה כדי לצפות בסטטוס ובתקלות.', email: 'עדכונים בדוא״ל', emailBody: 'אשרו את כתובת הדוא״ל לקבלת עדכוני סטטוס.', consent: 'אני מסכים לעיבוד הנדרש לפעולה זו.', done: 'סיום' },
  it: { loading: 'Caricamento pagina di stato', notFound: 'Pagina di stato non trovata', unavailable: 'Stato temporaneamente non disponibile.', retry: 'Riprova.', goTo: 'Vai a SSLPing', close: 'Chiudi', follow: 'Segui', thanks: 'Grazie per la segnalazione.', duplicate: 'Questa segnalazione è già stata ricevuta di recente.', processing: 'Elaborazione…', privacy: 'Privacy', privacyBody: 'Questa pagina tratta solo i dati necessari per mostrare lo stato del servizio.', cookies: 'Cookie', cookiesBody: "L'archiviazione necessaria ricorda la scelta; analisi opzionali solo con consenso.", password: 'Pagina di stato protetta da password', passwordBody: 'Inserisci la password per vedere stato e incidenti.', email: 'Aggiornamenti e-mail', emailBody: "Conferma l'indirizzo e-mail per ricevere gli avvisi di stato.", consent: 'Acconsento al trattamento necessario per questa funzione.', done: 'Fatto' },
  ja: { loading: 'ステータスページを読み込み中', notFound: 'ステータスページが見つかりません', unavailable: '現在ステータスを取得できません。', retry: 'もう一度お試しください。', goTo: 'SSLPingへ移動', close: '閉じる', follow: 'フォロー', thanks: 'ご報告ありがとうございます。', duplicate: 'この報告は最近すでに受信しています。', processing: '処理中…', privacy: 'プライバシー', privacyBody: 'このページはサービス状態の表示に必要な情報のみを処理します。', cookies: 'Cookie', cookiesBody: '必須ストレージは選択を保存し、任意の分析は同意後のみ有効です。', password: 'パスワード保護されたステータスページ', passwordBody: '状態と障害を表示するにはパスワードを入力してください。', email: 'メール更新', emailBody: '状態通知を受け取るにはメールアドレスを確認してください。', consent: 'この機能に必要な処理に同意します。', done: '完了' },
  ms: { loading: 'Memuat halaman status', notFound: 'Halaman status tidak ditemui', unavailable: 'Status tidak tersedia buat sementara waktu.', retry: 'Cuba lagi.', goTo: 'Pergi ke SSLPing', close: 'Tutup', follow: 'Ikuti', thanks: 'Terima kasih atas laporan anda.', duplicate: 'Laporan ini telah diterima baru-baru ini.', processing: 'Sedang diproses…', privacy: 'Privasi', privacyBody: 'Halaman ini hanya memproses data yang diperlukan untuk memaparkan status perkhidmatan.', cookies: 'Kuki', cookiesBody: 'Storan penting mengingati pilihan anda; analitik pilihan hanya dengan persetujuan.', password: 'Halaman status dilindungi kata laluan', passwordBody: 'Masukkan kata laluan untuk melihat status dan insiden.', email: 'Kemas kini e-mel', emailBody: 'Sahkan alamat e-mel untuk menerima pemberitahuan status.', consent: 'Saya bersetuju dengan pemprosesan untuk ciri ini.', done: 'Selesai' },
  no: { loading: 'Laster statusside', notFound: 'Statussiden ble ikke funnet', unavailable: 'Status er midlertidig utilgjengelig.', retry: 'Prøv igjen.', goTo: 'Gå til SSLPing', close: 'Lukk', follow: 'Følg', thanks: 'Takk for rapporten.', duplicate: 'Denne rapporten er allerede mottatt nylig.', processing: 'Behandler…', privacy: 'Personvern', privacyBody: 'Denne siden behandler bare data som trengs for å vise tjenestestatus.', cookies: 'Informasjonskapsler', cookiesBody: 'Nødvendig lagring husker valget; valgfri analyse bare med samtykke.', password: 'Passordbeskyttet statusside', passwordBody: 'Skriv inn passordet for å se status og hendelser.', email: 'E-postoppdateringer', emailBody: 'Bekreft e-postadressen for å motta statusmeldinger.', consent: 'Jeg samtykker til behandlingen for denne funksjonen.', done: 'Ferdig' },
  fil: { loading: 'Nilo-load ang status page', notFound: 'Hindi nakita ang status page', unavailable: 'Pansamantalang hindi available ang status.', retry: 'Subukan muli.', goTo: 'Pumunta sa SSLPing', close: 'Isara', follow: 'Subaybayan', thanks: 'Salamat sa iyong ulat.', duplicate: 'Natanggap na kamakailan ang ulat na ito.', processing: 'Pinoproseso…', privacy: 'Privacy', privacyBody: 'Pinoproseso lamang ng page na ito ang datos na kailangan upang ipakita ang status ng serbisyo.', cookies: 'Cookies', cookiesBody: 'Tinatandaan ng kinakailangang storage ang pagpili; opsyonal na analytics kapag may pahintulot.', password: 'Status page na protektado ng password', passwordBody: 'Ilagay ang password para makita ang status at mga insidente.', email: 'Mga update sa email', emailBody: 'Kumpirmahin ang email address para makatanggap ng status alerts.', consent: 'Sumasang-ayon ako sa pagproseso para sa feature na ito.', done: 'Tapos' },
  ur: { loading: 'اسٹیٹس صفحہ لوڈ ہو رہا ہے', notFound: 'اسٹیٹس صفحہ نہیں ملا', unavailable: 'حالت فی الحال دستیاب نہیں۔', retry: 'دوبارہ کوشش کریں۔', goTo: 'SSLPing پر جائیں', close: 'بند کریں', follow: 'فالو کریں', thanks: 'رپورٹ کا شکریہ۔', duplicate: 'یہ رپورٹ حال ہی میں موصول ہو چکی ہے۔', processing: 'کارروائی جاری ہے…', privacy: 'رازداری', privacyBody: 'یہ صفحہ صرف سروس کی حالت دکھانے کے لیے ضروری معلومات استعمال کرتا ہے۔', cookies: 'کوکیز', cookiesBody: 'ضروری ذخیرہ آپ کا انتخاب یاد رکھتا ہے؛ اختیاری تجزیہ صرف رضامندی سے۔', password: 'پاس ورڈ سے محفوظ اسٹیٹس صفحہ', passwordBody: 'حالت اور واقعات دیکھنے کے لیے پاس ورڈ درج کریں۔', email: 'ای میل اپ ڈیٹس', emailBody: 'حالت کی اطلاعات کے لیے ای میل پتے کی تصدیق کریں۔', consent: 'میں اس خصوصیت کے لیے ضروری کارروائی سے متفق ہوں۔', done: 'مکمل' },
  pl: { loading: 'Ładowanie strony stanu', notFound: 'Nie znaleziono strony stanu', unavailable: 'Stan jest chwilowo niedostępny.', retry: 'Spróbuj ponownie.', goTo: 'Przejdź do SSLPing', close: 'Zamknij', follow: 'Obserwuj', thanks: 'Dziękujemy za zgłoszenie.', duplicate: 'To zgłoszenie zostało niedawno odebrane.', processing: 'Przetwarzanie…', privacy: 'Prywatność', privacyBody: 'Ta strona przetwarza tylko dane potrzebne do pokazania stanu usługi.', cookies: 'Pliki cookie', cookiesBody: 'Niezbędne przechowywanie zapamiętuje wybór; opcjonalna analityka tylko za zgodą.', password: 'Strona stanu chroniona hasłem', passwordBody: 'Wpisz hasło, aby zobaczyć stan i incydenty.', email: 'Aktualizacje e-mail', emailBody: 'Potwierdź adres e-mail, aby otrzymywać powiadomienia.', consent: 'Wyrażam zgodę na przetwarzanie wymagane dla tej funkcji.', done: 'Gotowe' },
  ro: { loading: 'Se încarcă pagina de stare', notFound: 'Pagina de stare nu a fost găsită', unavailable: 'Starea nu este disponibilă momentan.', retry: 'Încearcă din nou.', goTo: 'Mergi la SSLPing', close: 'Închide', follow: 'Urmărește', thanks: 'Mulțumim pentru raport.', duplicate: 'Acest raport a fost primit deja recent.', processing: 'Se procesează…', privacy: 'Confidențialitate', privacyBody: 'Această pagină procesează doar datele necesare afișării stării serviciului.', cookies: 'Cookie-uri', cookiesBody: 'Stocarea necesară reține alegerea; analize opționale doar cu acord.', password: 'Pagină de stare protejată prin parolă', passwordBody: 'Introdu parola pentru a vedea starea și incidentele.', email: 'Actualizări prin e-mail', emailBody: 'Confirmă adresa de e-mail pentru a primi notificări.', consent: 'Sunt de acord cu prelucrarea necesară acestei funcții.', done: 'Gata' },
  sr: { loading: 'Учитавање странице статуса', notFound: 'Страница статуса није пронађена', unavailable: 'Статус тренутно није доступан.', retry: 'Покушајте поново.', goTo: 'Идите на SSLPing', close: 'Затвори', follow: 'Прати', thanks: 'Хвала на пријави.', duplicate: 'Ова пријава је недавно већ примљена.', processing: 'Обрада…', privacy: 'Приватност', privacyBody: 'Ова страница обрађује само податке потребне за приказ статуса услуге.', cookies: 'Колачићи', cookiesBody: 'Неопходно складиште памти избор; опциона аналитика само уз сагласност.', password: 'Страница статуса заштићена лозинком', passwordBody: 'Унесите лозинку за приказ статуса и инцидената.', email: 'Ажурирања е-поштом', emailBody: 'Потврдите адресу е-поште за обавештења.', consent: 'Пристајем на обраду потребну за ову функцију.', done: 'Готово' },
  sv: { loading: 'Laddar statussida', notFound: 'Statussidan hittades inte', unavailable: 'Statusen är tillfälligt otillgänglig.', retry: 'Försök igen.', goTo: 'Gå till SSLPing', close: 'Stäng', follow: 'Följ', thanks: 'Tack för din rapport.', duplicate: 'Rapporten har redan tagits emot nyligen.', processing: 'Bearbetar…', privacy: 'Integritet', privacyBody: 'Den här sidan behandlar bara data som krävs för att visa tjänstens status.', cookies: 'Cookies', cookiesBody: 'Nödvändig lagring minns valet; valfri analys endast med samtycke.', password: 'Lösenordsskyddad statussida', passwordBody: 'Ange lösenordet för att se status och incidenter.', email: 'E-postuppdateringar', emailBody: 'Bekräfta e-postadressen för att få statusmeddelanden.', consent: 'Jag samtycker till behandlingen för den här funktionen.', done: 'Klar' },
  sl: { loading: 'Nalaganje strani s stanjem', notFound: 'Strani s stanjem ni bilo mogoče najti', unavailable: 'Stanje trenutno ni na voljo.', retry: 'Poskusite znova.', goTo: 'Pojdi na SSLPing', close: 'Zapri', follow: 'Spremljaj', thanks: 'Hvala za prijavo.', duplicate: 'Ta prijava je bila nedavno že prejeta.', processing: 'Obdelava…', privacy: 'Zasebnost', privacyBody: 'Ta stran obdeluje le podatke, potrebne za prikaz stanja storitve.', cookies: 'Piškotki', cookiesBody: 'Nujna shramba si zapomni izbiro; neobvezna analitika le s soglasjem.', password: 'Stran s stanjem, zaščitena z geslom', passwordBody: 'Vnesite geslo za ogled stanja in incidentov.', email: 'E-poštne posodobitve', emailBody: 'Potrdite e-poštni naslov za prejemanje obvestil.', consent: 'Strinjam se z obdelavo za to funkcijo.', done: 'Končano' },
  sk: { loading: 'Načítava sa stavová stránka', notFound: 'Stavová stránka sa nenašla', unavailable: 'Stav momentálne nie je dostupný.', retry: 'Skúste to znova.', goTo: 'Prejsť na SSLPing', close: 'Zavrieť', follow: 'Sledovať', thanks: 'Ďakujeme za hlásenie.', duplicate: 'Toto hlásenie sme nedávno prijali.', processing: 'Spracúva sa…', privacy: 'Súkromie', privacyBody: 'Táto stránka spracúva iba údaje potrebné na zobrazenie stavu služby.', cookies: 'Súbory cookie', cookiesBody: 'Nevyhnutné úložisko si pamätá voľbu; voliteľná analytika len so súhlasom.', password: 'Stavová stránka chránená heslom', passwordBody: 'Zadajte heslo na zobrazenie stavu a incidentov.', email: 'E-mailové aktualizácie', emailBody: 'Potvrďte e-mailovú adresu na prijímanie oznámení.', consent: 'Súhlasím so spracovaním pre túto funkciu.', done: 'Hotovo' },
  tr: { loading: 'Durum sayfası yükleniyor', notFound: 'Durum sayfası bulunamadı', unavailable: 'Durum şu anda kullanılamıyor.', retry: 'Tekrar deneyin.', goTo: "SSLPing'e git", close: 'Kapat', follow: 'Takip et', thanks: 'Bildiriminiz için teşekkürler.', duplicate: 'Bu bildirim kısa süre önce alındı.', processing: 'İşleniyor…', privacy: 'Gizlilik', privacyBody: 'Bu sayfa yalnızca hizmet durumunu göstermek için gereken verileri işler.', cookies: 'Çerezler', cookiesBody: 'Gerekli depolama seçiminizi hatırlar; isteğe bağlı analiz yalnızca onayla.', password: 'Parola korumalı durum sayfası', passwordBody: 'Durum ve olayları görmek için parolayı girin.', email: 'E-posta güncellemeleri', emailBody: 'Durum bildirimleri için e-posta adresinizi doğrulayın.', consent: 'Bu özellik için gerekli işlemeyi kabul ediyorum.', done: 'Tamam' },
  uk: { loading: 'Завантаження статус-сторінки', notFound: 'Статус-сторінку не знайдено', unavailable: 'Стан зараз недоступний.', retry: 'Спробуйте ще раз.', goTo: 'Перейти до SSLPing', close: 'Закрити', follow: 'Стежити', thanks: 'Дякуємо за повідомлення.', duplicate: 'Це повідомлення вже нещодавно отримано.', processing: 'Обробка…', privacy: 'Конфіденційність', privacyBody: 'Ця сторінка обробляє лише дані, потрібні для показу стану сервісу.', cookies: 'Файли cookie', cookiesBody: 'Необхідне сховище запам’ятовує вибір; необов’язкова аналітика лише за згодою.', password: 'Статус-сторінка, захищена паролем', passwordBody: 'Введіть пароль, щоб переглянути стан та інциденти.', email: 'Оновлення електронною поштою', emailBody: 'Підтвердьте адресу електронної пошти для отримання сповіщень.', consent: 'Я погоджуюся на обробку, потрібну для цієї функції.', done: 'Готово' },
}

interface ActionCopy {
  cookieConsent: string
  necessaryOnly: string
  acceptOptional: string
  poweredBy: string
  sendConfirmation: string
  checkInbox: string
}

const actionCopy: Record<ExtendedStatusPageLanguage, ActionCopy> = {
  de: { cookieConsent: 'Cookie-Einwilligung', necessaryOnly: 'Nur notwendige', acceptOptional: 'Optionale akzeptieren', poweredBy: 'Bereitgestellt von', sendConfirmation: 'Bestätigungs-E-Mail senden', checkInbox: 'Posteingang prüfen' },
  nl: { cookieConsent: 'Cookie-toestemming', necessaryOnly: 'Alleen noodzakelijk', acceptOptional: 'Optionele accepteren', poweredBy: 'Mogelijk gemaakt door', sendConfirmation: 'Bevestigingsmail verzenden', checkInbox: 'Controleer uw inbox' },
  cs: { cookieConsent: 'Souhlas se soubory cookie', necessaryOnly: 'Pouze nezbytné', acceptOptional: 'Přijmout volitelné', poweredBy: 'Provozuje', sendConfirmation: 'Odeslat potvrzovací e-mail', checkInbox: 'Zkontrolujte doručenou poštu' },
  da: { cookieConsent: 'Cookiesamtykke', necessaryOnly: 'Kun nødvendige', acceptOptional: 'Acceptér valgfri', poweredBy: 'Leveret af', sendConfirmation: 'Send bekræftelsesmail', checkInbox: 'Tjek din indbakke' },
  fi: { cookieConsent: 'Evästesuostumus', necessaryOnly: 'Vain välttämättömät', acceptOptional: 'Hyväksy valinnaiset', poweredBy: 'Palvelun tarjoaa', sendConfirmation: 'Lähetä vahvistusviesti', checkInbox: 'Tarkista saapuneet' },
  el: { cookieConsent: 'Συγκατάθεση για cookies', necessaryOnly: 'Μόνο απαραίτητα', acceptOptional: 'Αποδοχή προαιρετικών', poweredBy: 'Με την υποστήριξη του', sendConfirmation: 'Αποστολή email επιβεβαίωσης', checkInbox: 'Ελέγξτε τα εισερχόμενά σας' },
  hr: { cookieConsent: 'Privola za kolačiće', necessaryOnly: 'Samo nužni', acceptOptional: 'Prihvati neobavezne', poweredBy: 'Omogućuje', sendConfirmation: 'Pošalji e-poruku za potvrdu', checkInbox: 'Provjerite ulaznu poštu' },
  hu: { cookieConsent: 'Cookie-hozzájárulás', necessaryOnly: 'Csak a szükségesek', acceptOptional: 'Opcionálisak elfogadása', poweredBy: 'Működteti', sendConfirmation: 'Megerősítő e-mail küldése', checkInbox: 'Ellenőrizze a beérkező leveleket' },
  he: { cookieConsent: 'הסכמה לקובצי Cookie', necessaryOnly: 'הכרחיים בלבד', acceptOptional: 'אישור אופציונליים', poweredBy: 'מופעל באמצעות', sendConfirmation: 'שליחת הודעת אישור', checkInbox: 'בדקו את תיבת הדואר' },
  it: { cookieConsent: 'Consenso ai cookie', necessaryOnly: 'Solo necessari', acceptOptional: 'Accetta opzionali', poweredBy: 'Offerto da', sendConfirmation: 'Invia email di conferma', checkInbox: 'Controlla la posta in arrivo' },
  ja: { cookieConsent: 'Cookieへの同意', necessaryOnly: '必須のみ', acceptOptional: '任意項目を許可', poweredBy: '提供', sendConfirmation: '確認メールを送信', checkInbox: '受信トレイを確認' },
  ms: { cookieConsent: 'Persetujuan kuki', necessaryOnly: 'Yang penting sahaja', acceptOptional: 'Terima analitik pilihan', poweredBy: 'Dikuasakan oleh', sendConfirmation: 'Hantar e-mel pengesahan', checkInbox: 'Semak peti masuk' },
  no: { cookieConsent: 'Samtykke til informasjonskapsler', necessaryOnly: 'Bare nødvendige', acceptOptional: 'Godta valgfrie', poweredBy: 'Levert av', sendConfirmation: 'Send bekreftelses-e-post', checkInbox: 'Sjekk innboksen' },
  fil: { cookieConsent: 'Pahintulot sa cookies', necessaryOnly: 'Kinakailangan lamang', acceptOptional: 'Tanggapin ang opsyonal', poweredBy: 'Pinapagana ng', sendConfirmation: 'Ipadala ang confirmation email', checkInbox: 'Tingnan ang inbox' },
  ur: { cookieConsent: 'کوکیز کی رضامندی', necessaryOnly: 'صرف ضروری', acceptOptional: 'اختیاری قبول کریں', poweredBy: 'فراہم کردہ', sendConfirmation: 'تصدیقی ای میل بھیجیں', checkInbox: 'اپنا ان باکس دیکھیں' },
  pl: { cookieConsent: 'Zgoda na pliki cookie', necessaryOnly: 'Tylko niezbędne', acceptOptional: 'Akceptuj opcjonalne', poweredBy: 'Obsługiwane przez', sendConfirmation: 'Wyślij e-mail potwierdzający', checkInbox: 'Sprawdź skrzynkę odbiorczą' },
  ro: { cookieConsent: 'Consimțământ pentru cookie-uri', necessaryOnly: 'Doar cele necesare', acceptOptional: 'Acceptă opționale', poweredBy: 'Oferit de', sendConfirmation: 'Trimite e-mailul de confirmare', checkInbox: 'Verifică mesajele primite' },
  sr: { cookieConsent: 'Сагласност за колачиће', necessaryOnly: 'Само неопходни', acceptOptional: 'Прихвати опционе', poweredBy: 'Покреће', sendConfirmation: 'Пошаљи е-поруку за потврду', checkInbox: 'Проверите пријемно сандуче' },
  sv: { cookieConsent: 'Samtycke till cookies', necessaryOnly: 'Endast nödvändiga', acceptOptional: 'Godkänn valfria', poweredBy: 'Drivs av', sendConfirmation: 'Skicka bekräftelsemeddelande', checkInbox: 'Kontrollera inkorgen' },
  sl: { cookieConsent: 'Soglasje za piškotke', necessaryOnly: 'Samo nujni', acceptOptional: 'Sprejmi neobvezne', poweredBy: 'Poganja', sendConfirmation: 'Pošlji potrditveno e-pošto', checkInbox: 'Preverite nabiralnik' },
  sk: { cookieConsent: 'Súhlas so súbormi cookie', necessaryOnly: 'Iba nevyhnutné', acceptOptional: 'Prijať voliteľné', poweredBy: 'Prevádzkuje', sendConfirmation: 'Odoslať potvrdzovací e-mail', checkInbox: 'Skontrolujte doručenú poštu' },
  tr: { cookieConsent: 'Çerez onayı', necessaryOnly: 'Yalnızca gerekli', acceptOptional: 'İsteğe bağlıları kabul et', poweredBy: 'Sağlayan', sendConfirmation: 'Onay e-postası gönder', checkInbox: 'Gelen kutunuzu kontrol edin' },
  uk: { cookieConsent: 'Згода на файли cookie', necessaryOnly: 'Лише необхідні', acceptOptional: 'Прийняти необов’язкові', poweredBy: 'Працює на', sendConfirmation: 'Надіслати лист підтвердження', checkInbox: 'Перевірте вхідні' },
}

function completeCopy(core: CoreCopy, supplemental: SupplementalCopy, actions: ActionCopy): PublicStatusCopy {
  return {
    loadingStatusPage: core.loadingStatusPage ?? supplemental.loading,
    statusPageNotFound: core.statusPageNotFound ?? supplemental.notFound,
    unableToLoadStatus: core.unableToLoadStatus ?? supplemental.unavailable,
    statusPageUnavailable: core.statusPageUnavailable ?? supplemental.unavailable,
    latestStatusUnavailable: core.latestStatusUnavailable ?? supplemental.unavailable,
    addressIncomplete: core.addressIncomplete ?? supplemental.notFound,
    checkAddress: core.checkAddress ?? supplemental.retry,
    monitoringUnavailable: core.monitoringUnavailable ?? supplemental.unavailable,
    tryAgain: core.tryAgain ?? supplemental.retry,
    goToSSLPing: core.goToSSLPing ?? supplemental.goTo,
    poweredBy: core.poweredBy ?? actions.poweredBy,
    millisecondsShort: core.millisecondsShort ?? 'ms',
    subscriptionConfirmationSent: core.subscriptionConfirmationSent ?? supplemental.emailBody,
    subscriptionError: core.subscriptionError ?? supplemental.unavailable,
    close: core.close ?? supplemental.close,
    currentStatus: core.currentStatus ?? supplemental.loading,
    updated: core.updated ?? supplemental.processing,
    overallUptime: core.overallUptime ?? core.uptime24h ?? supplemental.loading,
    last24Hours: core.last24Hours ?? core.uptime24h ?? supplemental.loading,
    services: core.services ?? supplemental.loading,
    operational: core.operational ?? core.overall.up.title,
    activeIncidents: core.activeIncidents ?? core.overall.down.title,
    publishedUpdates: core.publishedUpdates ?? core.latestUpdates ?? supplemental.loading,
    liveMonitoring: core.liveMonitoring ?? supplemental.loading,
    components: core.components ?? core.services ?? supplemental.loading,
    followMonitor: core.followMonitor ?? supplemental.follow,
    noComponents: core.noComponents ?? supplemental.notFound,
    noComponentsBody: core.noComponentsBody ?? supplemental.unavailable,
    latestUpdates: core.latestUpdates ?? supplemental.loading,
    incidentsAndAnnouncements: core.incidentsAndAnnouncements ?? core.latestUpdates ?? supplemental.loading,
    noIncidents: core.noIncidents ?? core.overall.up.title,
    noIncidentsBody: core.noIncidentsBody ?? core.overall.up.description,
    lastChecked: core.lastChecked ?? supplemental.processing,
    waitingForFirstCheck: core.waitingForFirstCheck ?? supplemental.processing,
    uptime24h: core.uptime24h ?? core.last24Hours ?? supplemental.loading,
    averageResponseTime: core.averageResponseTime ?? supplemental.loading,
    averageShort: core.averageShort ?? core.averageResponseTime ?? supplemental.loading,
    fastest: core.fastest ?? core.averageResponseTime ?? supplemental.loading,
    slowest: core.slowest ?? core.averageResponseTime ?? supplemental.loading,
    last24HoursShort: core.last24HoursShort ?? core.last24Hours ?? '24 h',
    highResponseTime: core.highResponseTime ?? core.averageResponseTime ?? supplemental.loading,
    activityAndResponse: core.activityAndResponse ?? core.averageResponseTime ?? supplemental.loading,
    visitorReports: core.visitorReports ?? core.reportProblem ?? supplemental.follow,
    baseline: core.baseline ?? core.averageShort ?? supplemental.loading,
    responseTime: core.responseTime ?? core.averageResponseTime ?? supplemental.loading,
    reportProblem: core.reportProblem ?? supplemental.follow,
    selectIssue: core.selectIssue ?? core.reportProblem ?? supplemental.follow,
    reportNotWorking: core.reportNotWorking ?? core.overall.down.title,
    reportSlow: core.reportSlow ?? core.overall.degraded.title,
    reportThanks: core.reportThanks ?? supplemental.thanks,
    reportThanksBody: core.reportThanksBody ?? supplemental.thanks,
    reportError: core.reportError ?? supplemental.unavailable,
    reportAlreadySent: core.reportAlreadySent ?? supplemental.duplicate,
    reportVerifying: core.reportVerifying ?? supplemental.processing,
    reportProcessing: core.reportProcessing ?? supplemental.processing,
    reportProcessingBody: core.reportProcessingBody ?? supplemental.processing,
    reportReceiptTitle: core.reportReceiptTitle ?? supplemental.thanks,
    reportReceiptSignal: core.reportReceiptSignal ?? core.reportProblem ?? supplemental.follow,
    reportReceiptTime: core.reportReceiptTime ?? core.updated ?? supplemental.processing,
    resolved: core.resolved ?? core.overall.up.title,
    subscribeToUpdates: core.subscribeToUpdates ?? supplemental.email,
    stayInformed: core.stayInformed ?? core.subscribeToUpdates ?? supplemental.email,
    emailUpdates: core.emailUpdates ?? supplemental.email,
    emailUpdatesBody: core.emailUpdatesBody ?? supplemental.emailBody,
    subscribe: core.subscribe ?? supplemental.email,
    privacy: core.privacy ?? supplemental.privacy,
    cookieSettings: core.cookieSettings ?? supplemental.cookies,
    generated: core.generated ?? supplemental.processing,
    footerLabel: core.footerLabel ?? supplemental.privacy,
    privacyNotice: core.privacyNotice ?? supplemental.privacy,
    privacyBody: core.privacyBody ?? supplemental.privacyBody,
    emailSubscriptions: core.emailSubscriptions ?? supplemental.email,
    emailSubscriptionsBody: core.emailSubscriptionsBody ?? supplemental.emailBody,
    cookies: core.cookies ?? supplemental.cookies,
    cookiesBody: core.cookiesBody ?? supplemental.cookiesBody,
    understood: core.understood ?? supplemental.done,
    cookieConsent: core.cookieConsent ?? actions.cookieConsent,
    privacyChoice: core.privacyChoice ?? supplemental.privacy,
    privacyChoiceBody: core.privacyChoiceBody ?? supplemental.privacyBody,
    readPrivacyNotice: core.readPrivacyNotice ?? supplemental.privacy,
    necessaryOnly: core.necessaryOnly ?? actions.necessaryOnly,
    acceptOptional: core.acceptOptional ?? actions.acceptOptional,
    privatePage: core.privatePage ?? supplemental.password,
    passwordPrompt: core.passwordPrompt ?? supplemental.passwordBody,
    password: core.password ?? supplemental.password,
    passwordPlaceholder: core.passwordPlaceholder ?? supplemental.password,
    unlocking: core.unlocking ?? supplemental.processing,
    viewStatusPage: core.viewStatusPage ?? core.currentStatus ?? supplemental.loading,
    passwordSecurity: core.passwordSecurity ?? supplemental.passwordBody,
    protectedPage: core.protectedPage ?? supplemental.password,
    passwordRejected: core.passwordRejected ?? supplemental.unavailable,
    incorrectPassword: core.incorrectPassword ?? supplemental.unavailable,
    subscribeTitle: core.subscribeTitle ?? core.subscribeToUpdates ?? supplemental.email,
    subscriptionIntro: core.subscriptionIntro ?? supplemental.emailBody,
    emailAddress: core.emailAddress ?? supplemental.email,
    subscriptionConsent: core.subscriptionConsent ?? supplemental.consent,
    subscriptionConsentRequired: core.subscriptionConsentRequired ?? supplemental.consent,
    subscribing: core.subscribing ?? supplemental.processing,
    sendConfirmation: core.sendConfirmation ?? actions.sendConfirmation,
    checkInbox: core.checkInbox ?? actions.checkInbox,
    done: core.done ?? supplemental.done,
    overall: core.overall,
  }
}

export const extendedPublicStatusCopy: Record<ExtendedStatusPageLanguage, PublicStatusCopy> = {
  de: completeCopy(extendedPublicStatusCore.de, supplementalCopy.de, actionCopy.de),
  nl: completeCopy(extendedPublicStatusCore.nl, supplementalCopy.nl, actionCopy.nl),
  cs: completeCopy(extendedPublicStatusCore.cs, supplementalCopy.cs, actionCopy.cs),
  da: completeCopy(extendedPublicStatusCore.da, supplementalCopy.da, actionCopy.da),
  fi: completeCopy(extendedPublicStatusCore.fi, supplementalCopy.fi, actionCopy.fi),
  el: completeCopy(extendedPublicStatusCore.el, supplementalCopy.el, actionCopy.el),
  hr: completeCopy(extendedPublicStatusCore.hr, supplementalCopy.hr, actionCopy.hr),
  hu: completeCopy(extendedPublicStatusCore.hu, supplementalCopy.hu, actionCopy.hu),
  he: completeCopy(extendedPublicStatusCore.he, supplementalCopy.he, actionCopy.he),
  it: completeCopy(extendedPublicStatusCore.it, supplementalCopy.it, actionCopy.it),
  ja: completeCopy(extendedPublicStatusCore.ja, supplementalCopy.ja, actionCopy.ja),
  ms: completeCopy(extendedPublicStatusCore.ms, supplementalCopy.ms, actionCopy.ms),
  no: completeCopy(extendedPublicStatusCore.no, supplementalCopy.no, actionCopy.no),
  fil: completeCopy(extendedPublicStatusCore.fil, supplementalCopy.fil, actionCopy.fil),
  ur: completeCopy(extendedPublicStatusCore.ur, supplementalCopy.ur, actionCopy.ur),
  pl: completeCopy(extendedPublicStatusCore.pl, supplementalCopy.pl, actionCopy.pl),
  ro: completeCopy(extendedPublicStatusCore.ro, supplementalCopy.ro, actionCopy.ro),
  sr: completeCopy(extendedPublicStatusCore.sr, supplementalCopy.sr, actionCopy.sr),
  sv: completeCopy(extendedPublicStatusCore.sv, supplementalCopy.sv, actionCopy.sv),
  sl: completeCopy(extendedPublicStatusCore.sl, supplementalCopy.sl, actionCopy.sl),
  sk: completeCopy(extendedPublicStatusCore.sk, supplementalCopy.sk, actionCopy.sk),
  tr: completeCopy(extendedPublicStatusCore.tr, supplementalCopy.tr, actionCopy.tr),
  uk: completeCopy(extendedPublicStatusCore.uk, supplementalCopy.uk, actionCopy.uk),
}
